; Script generated by Inno Setup Script Wizard.
#define MyAppName "ModelPeek"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "ModelPeek Team"
#define MyAppURL "https://github.com/ModelPeek"

[Setup]
AppId={{D37F2633-149C-4CD8-B60F-FCE3B40B7E98}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=ModelPeek_Setup_v1.0.0
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin

[Languages]
Name: "chinesesimp"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Files]
Source: "..\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Run]
Filename: "{sys}\regsvr32.exe"; Parameters: "/s ""{app}\ModelPeekExtension.dll"""; StatusMsg: "正在注册 ModelPeek 资源管理器扩展组件..."; Flags: runhidden

[UninstallRun]
Filename: "{sys}\regsvr32.exe"; Parameters: "/u /s ""{app}\ModelPeekExtension.dll"""; StatusMsg: "正在注销 ModelPeek 资源管理器扩展组件..."; Flags: runhidden
Filename: "taskkill.exe"; Parameters: "/f /im prevhost.exe"; Flags: runhidden
